### PR TITLE
Pandas

### PR DESCRIPTION
**Pull request by cdhinrichs**
This PR is related to Issue #182. It does the following:
- Adds a `ignore_index=True` argument to calls to `pd.concat` which effectively does the same thing that `details.reset_index(drop=True)` would have done, but without the extra line of code.
- Changed the declaration of the `details` dataframe so that the first 2 columns, `layer_id` and `name` are specified to appear first after the dataframe is created. The same treatment is given to the `distances` dataframe.

The problem was, previously `details` was created as, 
```python
details = pd.DataFrame(columns=['layer_id', 'name'])
```
This had the effect of making those two columns come first, as desired. However, since they are empty columns with no data, pandas assigns them the generic `dtype='object'`. Later, when a real column is added, it has to reconcile the type of the new data with the old, and this is where the `FutureWarning` is emitted. 

The new way is to create `details` with an empty columns list, and then re-order the columns at the end like so:
```python
        # Reorder the columns so that layer_id and name come first.
        lead_cols = ["layer_id", "name"]
        details = details[lead_cols + [c for c in details.columns if not c in lead_cols]]
```
I checked that the order of columns in the `details` is exactly the same as it was before this PR, which is:
```
Index(['layer_id', 'name', 'D', 'Lambda', 'M', 'N', 'Q', 'W_scale', 'alpha',
       'alpha_weighted', 'best_fit', 'bulk_max', 'bulk_min', 'entropy',
       'fit_entropy', 'has_esd', 'lambda_max', 'layer_type', 'log_alpha_norm',
       'log_norm', 'log_spectral_norm', 'longname', 'matrix_rank',
       'mp_softrank', 'norm', 'num_evals', 'num_fingers', 'num_pl_spikes',
       'num_spikes', 'rank_loss', 'rf', 'sigma', 'sigma_mp', 'spectral_norm',
       'stable_rank', 'sv_max', 'warning', 'weak_rank_loss', 'xmax', 'xmin'],
      dtype='object')
```
All tests that generated that Warning have been re-run and verified that they do not generate it any more, and that they give the same result as before. Currently, `test_compute_alphas` is failing because the fast SVD method is no longer accurate to within 4 decimal places of the expected value.

### CODE REVIEW

**Comment by charlesmartin14** [comment]
We have to check the example notebooks to make sure this change in the index does not break the examples

**Comment by cdhinrichs** [comment]
If the order of columns is the same, is there any other way it could break them?

**Comment by charlesmartin14** [comment]
If the dataframe is exactly the same it shoudl be fine
If any  columns changed, then ll bets are off

Thanks

**Comment by charlesmartin14** [comment]
Is there a specific existing unit test (or tests) that can verify the changes don't break anything ?

**Comment by charlesmartin14** [comment]
There appear to be 2 entire suites of Tests missing from the BuildWeightWatcher notebook

Test_VGG11_noModel
Test_VGG11_Distances

**Pull request merged**
